apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: indexer-certs
  namespace: wazuh
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: indexer-certs
    creationPolicy: Owner
  data:
    - secretKey: root-ca.pem
      remoteRef:
        key: wazuh/certs/indexer_cluster
        property: root-ca.pem
    - secretKey: node.pem
      remoteRef:
        key: wazuh/certs/indexer_cluster
        property: node.pem
    - secretKey: node-key.pem
      remoteRef:
        key: wazuh/certs/indexer_cluster
        property: node-key.pem
    - secretKey: dashboard.pem
      remoteRef:
        key: wazuh/certs/indexer_cluster
        property: dashboard.pem
    - secretKey: dashboard-key.pem
      remoteRef:
        key: wazuh/certs/indexer_cluster
        property: dashboard-key.pem
    - secretKey: admin.pem
      remoteRef:
        key: wazuh/certs/indexer_cluster
        property: admin.pem
    - secretKey: admin-key.pem
      remoteRef:
        key: wazuh/certs/indexer_cluster
        property: admin-key.pem
    - secretKey: filebeat.pem
      remoteRef:
        key: wazuh/certs/indexer_cluster
        property: filebeat.pem
    - secretKey: filebeat-key.pem
      remoteRef:
        key: wazuh/certs/indexer_cluster
        property: filebeat-key.pem
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dashboard-certs
  namespace: wazuh
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: dashboard-certs
    creationPolicy: Owner
  data:
    - secretKey: cert.pem
      remoteRef:
        key: wazuh/certs/dashboard_http
        property: cert.pem
    - secretKey: key.pem
      remoteRef:
        key: wazuh/certs/dashboard_http
        property: key.pem
    - secretKey: root-ca.pem
      remoteRef:
        key: wazuh/certs/indexer_cluster
        property: root-ca.pem
